// Demo-modus: wordt gebruikt als de backend niet bereikbaar is (GitHub Pages)

export const DEMO_PROJECT = {
  id: 1,
  naam: 'Duitslandlaan',
  cl_nummer: '12345',
  datum: '2026-06-03',
  opdrachtgever: 'Liander',
  aannemer: 'Visser en Smit Hanab',
  status: 'concept',
  completeness: 72,
  block_count: 18,
};

const mkPb = (id, blockId, fase, domein, activiteit, inc_items, exc_items, variabele_velden, variabele_waarden, active_inc_items) => ({
  id,
  block_id: blockId,
  project_id: 1,
  sort_order: id,
  fase,
  domein,
  activiteit,
  inc_items,
  exc_items,
  variabele_velden: variabele_velden || [],
  variabele_waarden: variabele_waarden || {},
  active_inc_items: active_inc_items !== undefined ? active_inc_items : inc_items.map((_, i) => i),
  extra_exc_items: [],
  variabel: variabele_velden?.length > 0 ? 1 : 0,
});

export const DEMO_BLOCKS = [
  // PREP
  mkPb(1, 'PM-PREP-001', 'PREP', 'PM', 'BTO formaliseren',
    ['Opstellen en ondertekening BTO met opdrachtgever', 'Afstemming scope, planning en randvoorwaarden', '1× getekende BTO als projectstartsein'],
    ['Aanpassing BTO na formele gunning op verzoek opdrachtgever']),
  mkPb(2, 'PM-PREP-002', 'PREP', 'PM', 'Startbijeenkomst',
    ['Organiseren en faciliteren kickoff-meeting', 'Agenda opstellen, verslag uitwerken en distribueren', 'Introductie VISI-communicatieprotocol'],
    ['Reiskosten buiten de regio']),
  mkPb(3, 'PB-PREP-001', 'PREP', 'PB', 'Kwaliteitsplan VISI',
    ['Opstellen projectspecifiek kwaliteitsplan conform VISI-raamwerk', 'Beschrijving communicatielijnen en documentbeheer', 'Vaststelling rollenmatrix'],
    ['Implementatie VISI-software bij opdrachtgever']),
  mkPb(4, 'PB-PREP-002', 'PREP', 'PB', 'Tijdschema en risicoregister',
    ['Opstellen initieel projecttijdschema (Gantt) op mijlpaalniveau', 'Initieel risicoregister met top-10 risico\'s', 'Afstemming planning met opdrachtgever'],
    ['Probabilistische risicoquantificatie']),

  // VO / TM
  mkPb(5, 'TM-VO-001', 'VO', 'TM', 'VO tracé opstellen',
    ['1× leidingkaart schaal 1:500/1:1.000 in AutoCAD (.dwg) + PDF conform NLCS++ Netbeheer V12', '1× ontwerpnota met ontwerpkeuzes en materiaalbehoefte', 'Tracelengte: 1.250 m'],
    ['Re-engineering als gevolg van scopewijziging opdrachtgever', 'Kabeltechnische berekeningen'],
    ['Tracelengte (m)'], { 'Tracelengte (m)': '1.250' }),
  mkPb(6, 'TM-VO-003', 'VO', 'TM', 'KLIC-melding VO',
    ['Uitvoeren KLIC-melding voor het VO-tracé', 'Verwerken en digitaal archiveren van de KLIC-resultaten', 'Signaleren strijdigheden'],
    ['Meerdere KLIC-meldingen bij verlopen geldigheid']),
  mkPb(7, 'TM-VO-004', 'VO', 'TM', 'Schouwen tracé',
    ['Veldschouw van het voorkeursalternatief tracé met fotodocumentatie', 'Inventarisatie obstakels', 'Schouwrapportage'],
    ['Gedetailleerde bodemonderzoeken']),
  mkPb(8, 'TM-VO-005', 'VO', 'TM', 'Proefsleuven VO',
    ['Uitvoering proefsleuven à 1 m breed', 'Fotodocumentatie aangetroffen kabels & leidingen', 'Verslag proefsleuven', 'Aantal VO-proefsleuven: 5 st (tracelengte 1.250 m ÷ 250 m)'],
    ['Herstel straatwerk na proefsleuven'],
    ['Aantal VO-proefsleuven (st)'], { 'Aantal VO-proefsleuven (st)': '5' }),
  mkPb(9, 'TM-VO-006', 'VO', 'TM', 'Station engineering VO',
    ['Plaatsbepaling en opsteltekeningen MS-stations', 'Optierapport met ruimtebehoefte', 'Afstemming met gemeente over stationslocatie', 'Aantal stations: 3'],
    ['Civieltechnisch ontwerp fundering (aparte post DO)'],
    ['Aantal stations (st)'], { 'Aantal stations (st)': '3' }),
  mkPb(10, 'TM-VO-007', 'VO', 'TM', 'Belastbaarheids- en beïnvloedingsberekeningen',
    ['Thermische belastbaarheidsberekening conform NEN-EN 60287', 'Beïnvloedingsberekening voor parallelloopende kabels', 'Beïnvloedingsberekening per HDD-boring', 'Berekeningen gedocumenteerd in technisch rapport'],
    ['Dynamische vermogensstroomberekening', 'EMC-studie'],
    [], {},
    // Inc. item index 2 (HDD-boring) uitgeschakeld per testscenario
    [0, 1, 3]),

  // VO / OM
  mkPb(11, 'OM-VO-003', 'VO', 'OM', 'ZRO — Privaat eigenaar (perceel 1)',
    ['Identificatie percelen via BRK-kadasterinformatie', 'Eerste contact eigenaar en inventarisatie bezwaren', 'Concept ZRO opstellen', 'Kadastraal nr: LDN-A-1234 | Eigenaar: Fam. De Vries'],
    ['Notariële passering', 'Schaderegeling bij bezwaar'],
    ['Kadastrale aanduiding', 'Naam eigenaar'], { 'Kadastrale aanduiding': 'LDN-A-1234', 'Naam eigenaar': 'Fam. De Vries' }),
  mkPb(12, 'OM-VO-003', 'VO', 'OM', 'ZRO — Privaat eigenaar (perceel 2)',
    ['Identificatie percelen via BRK-kadasterinformatie', 'Eerste contact eigenaar en inventarisatie bezwaren', 'Concept ZRO opstellen', 'Kadastraal nr: LDN-A-1235 | Eigenaar: Stichting Grondbeheer Zuid'],
    ['Notariële passering'],
    ['Kadastrale aanduiding', 'Naam eigenaar'], { 'Kadastrale aanduiding': 'LDN-A-1235', 'Naam eigenaar': 'Stichting Grondbeheer Zuid' }),
  mkPb(13, 'OM-VO-005', 'VO', 'OM', 'ZRO — Hoogheemraadschap van Rijnland',
    ['Vooroverleg met Hoogheemraadschap van Rijnland over kruising watergang', 'Inventarisatie eisen watervergunning', 'Kruisinglocatie: Duitslandlaan km 1.1 — Vlietpolder'],
    ['Aanvraag watervergunning (aparte post DO)'],
    ['Kruisinglocatie'], { 'Kruisinglocatie': 'Duitslandlaan km 1.1 — Vlietpolder' }),

  // VO / CO
  mkPb(14, 'CO-VO-001', 'VO', 'CO', 'Quickscan Flora & Fauna (F&F)',
    ['Bureaustudie ecologische waarden en beschermde soorten langs het tracé', '1× quickscan-rapport met bevindingen en risicobeoordeling', 'Advies over noodzaak nader veldonderzoek'],
    ['Nader ecologisch veldonderzoek', 'Aanvraag ontheffing Wnb']),
  mkPb(15, 'CO-VO-003', 'VO', 'CO', 'Archeologisch bureauonderzoek',
    ['Bureauonderzoek conform KNA-protocol', 'Verwachtingskaart voor het plangebied', 'Advies selectiebesluit'],
    ['Inventariserend veldonderzoek archeologie', 'Opgraving bij vondsten']),
  mkPb(16, 'CO-VO-004', 'VO', 'CO', 'Bodemonderzoek NEN 5725/5740',
    ['Verkennend bodemonderzoek conform NEN 5725 en NEN 5740', 'Boorpuntenplan, monsteranalyses en bodemkwaliteitsrapportage', 'Beoordeling hergebruik vrijkomende grond'],
    ['Nader bodemonderzoek bij verontreiniging', 'Sanering aangetroffen verontreiniging']),

  // VO / PB
  mkPb(17, 'PB-VO-001', 'VO', 'PB', 'Documentmanagement VISI',
    ['Inrichten VISI-communicatieomgeving voor de VO-fase', 'Beheer en archivering projectdocumenten', 'Opleiding projectteamleden'],
    ['Softwarelicentie VISI-platform']),
  mkPb(18, 'PB-VO-004', 'VO', 'PB', 'Planning en voortgang VO',
    ['Opstellen en bewaken detailplanning VO-fase', 'Tweewekelijkse voortgangsrapportage', 'Bijstellen planning bij afwijkingen'],
    ['Planningsvertraging door scopewijziging']),
];

export const DEMO_ALL_BLOCKS = [
  { id: 'PM-PREP-001', fase: 'PREP', domein: 'PM', activiteit: 'BTO formaliseren', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PM-PREP-002', fase: 'PREP', domein: 'PM', activiteit: 'Startbijeenkomst', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-PREP-001', fase: 'PREP', domein: 'PB', activiteit: 'Kwaliteitsplan VISI', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-PREP-002', fase: 'PREP', domein: 'PB', activiteit: 'Tijdschema en risicoregister', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-001', fase: 'VO', domein: 'TM', activiteit: 'VO tracé opstellen', inc_items: [], exc_items: [], variabele_velden: ['Tracelengte (m)'], variabel: 1 },
  { id: 'TM-VO-002', fase: 'VO', domein: 'TM', activiteit: 'Oeversteken (HDD/gestuurde boring VO)', inc_items: [], exc_items: [], variabele_velden: ['Aantal oeversteken (st)'], variabel: 1 },
  { id: 'TM-VO-003', fase: 'VO', domein: 'TM', activiteit: 'KLIC-melding VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-004', fase: 'VO', domein: 'TM', activiteit: 'Schouwen tracé', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-005', fase: 'VO', domein: 'TM', activiteit: 'Proefsleuven VO', inc_items: [], exc_items: [], variabele_velden: ['Aantal VO-proefsleuven (st)'], variabel: 1 },
  { id: 'TM-VO-006', fase: 'VO', domein: 'TM', activiteit: 'Station engineering VO', inc_items: [], exc_items: [], variabele_velden: ['Aantal stations (st)'], variabel: 1 },
  { id: 'TM-VO-007', fase: 'VO', domein: 'TM', activiteit: 'Belastbaarheids- en beïnvloedingsberekeningen', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-008', fase: 'VO', domein: 'TM', activiteit: 'Materiaallijst VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-009', fase: 'VO', domein: 'TM', activiteit: 'VGM-O plan VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-010', fase: 'VO', domein: 'TM', activiteit: 'Vooroverleg 1', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-011', fase: 'VO', domein: 'TM', activiteit: 'Boorclub', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'TM-VO-012', fase: 'VO', domein: 'TM', activiteit: 'Eisenverificatie VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'OM-VO-001', fase: 'VO', domein: 'OM', activiteit: 'Stakeholderanalyse', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'OM-VO-002', fase: 'VO', domein: 'OM', activiteit: 'Vergunningeninventarisatie VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'OM-VO-003', fase: 'VO', domein: 'OM', activiteit: 'ZRO — Privaat eigenaar', inc_items: [], exc_items: [], variabele_velden: ['Kadastrale aanduiding','Naam eigenaar'], variabel: 1 },
  { id: 'OM-VO-004', fase: 'VO', domein: 'OM', activiteit: 'ZRO — Gemeente', inc_items: [], exc_items: [], variabele_velden: ['Kadastrale aanduiding','Naam gemeente'], variabel: 1 },
  { id: 'OM-VO-005', fase: 'VO', domein: 'OM', activiteit: 'ZRO — Hoogheemraadschap van Rijnland', inc_items: [], exc_items: [], variabele_velden: ['Kruisinglocatie'], variabel: 1 },
  { id: 'OM-VO-006', fase: 'VO', domein: 'OM', activiteit: 'ZRO — Rijkswaterstaat (RWS)', inc_items: [], exc_items: [], variabele_velden: ['Kruisinglocatie'], variabel: 1 },
  { id: 'OM-VO-007', fase: 'VO', domein: 'OM', activiteit: 'ZRO — ProRail', inc_items: [], exc_items: [], variabele_velden: ['Kruisinglocatie'], variabel: 1 },
  { id: 'OM-VO-008', fase: 'VO', domein: 'OM', activiteit: 'ZRO — Nutsbedrijf', inc_items: [], exc_items: [], variabele_velden: ['Naam beheerder'], variabel: 1 },
  { id: 'OM-VO-009', fase: 'VO', domein: 'OM', activiteit: 'Betredingstoestemmingen VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'CO-VO-001', fase: 'VO', domein: 'CO', activiteit: 'Quickscan Flora & Fauna (F&F)', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'CO-VO-002', fase: 'VO', domein: 'CO', activiteit: 'Quickscan NGE/OOO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'CO-VO-003', fase: 'VO', domein: 'CO', activiteit: 'Archeologisch bureauonderzoek', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'CO-VO-004', fase: 'VO', domein: 'CO', activiteit: 'Bodemonderzoek NEN 5725/5740', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'CO-VO-005', fase: 'VO', domein: 'CO', activiteit: 'Asbestonderzoek type A', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-001', fase: 'VO', domein: 'PB', activiteit: 'Documentmanagement VISI', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-002', fase: 'VO', domein: 'PB', activiteit: 'WBS en eisenanalyse', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-003', fase: 'VO', domein: 'PB', activiteit: 'Afwijkingenbeheer', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-004', fase: 'VO', domein: 'PB', activiteit: 'Planning en voortgang VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-005', fase: 'VO', domein: 'PB', activiteit: 'Risicomanagement VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PB-VO-006', fase: 'VO', domein: 'PB', activiteit: 'Financieel beheer VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
  { id: 'PM-VO-001', fase: 'VO', domein: 'PM', activiteit: 'BTO-vergaderingen en aansturing VO', inc_items: [], exc_items: [], variabele_velden: [], variabel: 0 },
];
